// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_sleep  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_win_create 22
#define SYS_win_destroy 23
#define SYS_win_poll 24
#define SYS_win_focus 25
#define SYS_win_get_focus 26
#define SYS_win_snapshot 27
#define SYS_draw_pixel 28
#define SYS_draw_rect 29
#define SYS_win_set_compositor 30
#define SYS_win_post_event 31
#define SYS_read_pixel 32
#define SYS_draw_bitmap 33
#define SYS_win_get_compositor 34
#define SYS_halt 35
#define SYS_win_move 36
